remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
include: ["_pages"]
plugins:
  - jekyll-include-cache
subtitle: "Version 2.0"
name: "Michael Rose"
description: "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
        sticky: true

author:
  name: "Jolanta Rieksta"
  avatar: "/assets/pic1.jpg"
  bio: "I am biologist investigating how plants function and respond to various stressors at
   high altitude and latitude ecosystems."
  location: "Copenhagen, Denmark"
  email: "jolanta.rieksta@bio.ku.dk"
  links:
    - label: "University of Copenhagen"
      icon: "fas fa-fw fa-university"
      url: "https://www1.bio.ku.dk/english/staff/?pure=en/persons/620322"
    - label: "Email: jolanta.rieksta@bio.ku.dk"
      icon: "fas fa-fw fa-envelope-square"
      url: "jolanta.rieskta@bio.ku.dk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/JRieksta"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jrieksta"


