remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
include: ["_pages"]
plugins:
  - jekyll-include-cache
subtitle: "Version 2.0"
name: "Michael Rose"
description: "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
        sticky: true

author:
  name: "Jolanta Rieksta"
  avatar: "/assets/images/pic1.jpeg"
  bio: "I am biologist investigating how plants function and respond to various stressors at high altitude and latitude ecosystems."
  location: "Copenhagen, Denmark"
  location: "Trondheim, Norway"
  email: "jolanta.rieksta@bio.ku.dk"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:john.doe@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/johndoe"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/JRieksta"
